title: Swapon Kanti Das
description:
theme: jekyll-theme-cayman # this  a free theme. I used from Cayman
url: https://swaponkantidas.github.io 
email: Swapon.Das@yahoo.com
social:
  email: Swapon.Das@yahoo.com
  github: swaponkantidas 
  linkedin: swapon-kanti-das
author:
  name: Swapon Kanti Das

footer:
  text: "Disclaimer: @ Swapon Kanti Das 2024."

