title: Swapon Kanti Das
description: Welcome to my portfolio! The purpose is to show case my skills.
theme: jekyll-theme-cayman # this  a free theme. I used from Cayman
url: https://swaponkantidas.github.io 
email: Swapon.Das@yahoo.com
social:
  email: Swapon.Das@yahoo.com
  github: swaponkantidas 
  linkedin: swapon-kanti-das
author:
  name: Swapon Kanti Das
  bio:
    👋 Hi, I’m Swapon Kanti Das
    👀 I’m interested in instructional design, learning & development, UI/UX, web development, and data analysis.
    🌱 I’m currently learning Python, HTML, CSS, JavaScript, R Program,
