title: Swapon Kanti Das
description: Welcome to my website!
theme: jekyll-theme-cayman # this  a free theme. I used from Cayman
url: https://swaponkantidas.github.io 
email: Swapon.Das@yahoo.com
social:
  email: Swapon.Das@yahoo.com
  github: https://github.com/swaponkantidas 
  linkedin: https://www.linkedin.com/in/swapon-kanti-das/ 
author:
  name: Swapon Kanti Das
  bio:
    👋 Hi, I’m Swapon Kanti Das
    👀 I’m interested in instructional design, learning & development, UI/UX, web development, and data analysis.
    🌱 I’m currently learning Python, HTML, CSS, JavaScript, R Program,
