title: Swapon Kanti Das
description: Personal portfolio for instructional design, L&D, UI/UX, web development, and data analysis.
theme: minima # You can replace this with any Jekyll theme of your choice
url: https://username.github.io # Replace 'username' with your GitHub username
email: Swapon.Das@yahoo.com
social:
  email: Swapon.Das@yahoo.com
  github: https://github.com/username # Replace 'username' with your GitHub username
  linkedin: https://www.linkedin.com/in/your-linkedin-username # Optional, replace with your LinkedIn profile
author:
  name: Swapon Kanti Das
  bio: |
    👋 Hi, I’m Swapon Kanti Das
    👀 I’m interested in instructional design, learning & development, UI/UX, web development, and data analysis.
    🌱 I’m currently learning Python, HTML, CSS, JavaScript, R Program,
